apostrophe_dict = {
"ain't": "am not / are not",
"aren't": "are_not",
"can't": "cannot",
"can't've": "cannot_have",
"'cause": "because",
"could've": "could_have",
"couldn't": "could_not",
"couldn't've": "could_not_have",
"didn't": "did_not",
"doesn't": "does_not",
"don't": "do_not",
"hadn't": "had_not",
"hadn't've": "had_not_have",
"hasn't": "has_not",
"haven't": "have_not",
"he'd": "he_had / he_would",
"he'd've": "he_would_have",
"he'll": "he_shall / he_will",
"he'll've": "he_shall_have / he_will_have",
"he's": "he_has / he_is",
"how'd": "how_did",
"how'd'y": "how_do_you",
"how'll": "how_will",
"how's": "how_has / how_is",
"i'd": "I_had / I_would",
"i'd've": "I_would_have",
"i'll": "I_shall / I_will",
"i'll've": "I_shall_have / I_will_have",
"i'm": "I_am",
"i've": "I_have",
"isn't": "is_not",
"it'd": "it_had / it would",
"it'd've": "it_would_have",
"it'll": "it_shall / it_will",
"it'll've": "it_shall_have / it_will_have",
"it's": "it_has / it_is",
"let's": "let_us",
"ma'am": "madam",
"mayn't": "may_ not",
"might've": "might_have",
"mightn't": "might_not",
"mightn't've": "might_not_have",
"must've": "must_have",
"mustn't": "must_not",
"mustn't've": "must_not_have",
"needn't": "need_not",
"needn't've": "need_not_have",
"o'clock": "of_the_clock",
"oughtn't": "ought_not",
"oughtn't've": "ought_not_have",
"shan't": "shall_not",
"sha'n't": "shall_not",
"shan't've": "shall_not_have",
"she'd": "she_had / she_would",
"she'd've": "she_would_have",
"she'll": "she_shall / she_will",
"she'll've": "she_shall_have / she_will_have",
"she's": "she_has / she_is",
"should've": "should_have",
"shouldn't": "should_not",
"shouldn't've": "should_not_have",
"so've": "so_have",
"so's": "so_as / so_is",
"that'd": "that_would / that_had",
"that'd've": "that_would_have",
"that's": "that_has / that_is",
"there'd": "there_had / there_would",
"there'd've": "there_would_have",
"there's": "there_has / there_is",
"they'd": "they_had / they_would",
"they'd've": "they_would_have",
"they'll": "they_shall / they_will",
"they'll've": "they_shall_have / they_will_have",
"they're": "they_are",
"they've": "they_have",
"to've": "to_have",
"wasn't": "was_not",
"we'd": "we_had / we_would",
"we'd've": "we_would_have",
"we'll": "we_will",
"we'll've": "we_will_have",
"we're": "we_are",
"we've": "we_have",
"weren't": "were_not",
"what'll": "what_shall / what_will",
"what'll've": "what_shall_have / what_will_have",
"what're": "what_are",
"what's": "what_has / what_is",
"what've": "what_have",
"when's": "when_has / when_is",
"when've": "when_have",
"where'd": "where_did",
"where's": "where_has / where_is",
"where've": "where_have",
"who'll": "who_shall / who_will",
"who'll've": "who_shall_have / who_will_have",
"who's": "who_has / who_is",
"who've": "who_have",
"why's": "why_has / why_is",
"why've": "why_have",
"will've": "will_have",
"won't": "will_not",
"won't've": "will_not_have",
"would've": "would_have",
"wouldn't": "would_not",
"wouldn't've": "would_not_have",
"y'all": "you_all",
"y'all'd": "you_all_would",
"y'all'd've": "you_all_would_have",
"y'all're": "you_all_are",
"y'all've": "you_all_have",
"you'd": "you_had / you_would",
"you'd've": "you_would_have",
"you'll": "you_shall / you_will",
"you'll've": "you_shall_have / you_will_have",
"you're": "you_are",
"you've": "you_have"
}



short_word_dict = {
"121": "one_to_one",
"a/s/l": "age, sex, location",
"adn": "any day now",
"afaik": "as far as I know",
"afk": "away from keyboard",
"aight": "alright",
"alol": "actually laughing out loud",
"b4": "before",
"b4n": "bye for now",
"bak": "back at the keyboard",
"bf": "boyfriend",
"bff": "best friends forever",
"bfn": "bye for now",
"bg": "big grin",
"bta": "but then again",
"btw": "by the way",
"cid": "crying in disgrace",
"cnp": "continued in my next post",
"cp": "chat post",
"cu": "see you",
"cul": "see you later",
"cul8r": "see you later",
"cya": "bye",
"cyo": "see you online",
"dbau": "doing business as usual",
"fud": "fear, uncertainty, and doubt",
"fwiw": "for what it's worth",
"fyi": "for your information",
"g": "grin",
"g2g": "got to go",
"ga": "go ahead",
"gal": "get a life",
"gf": "girlfriend",
"gfn": "gone for now",
"gmbo": "giggling my butt off",
"gmta": "great minds think alike",
"h8": "hate",
"hagn": "have a good night",
"hdop": "help delete online predators",
"hhis": "hanging head in shame",
"iac": "in any case",
"ianal": "I am not a lawyer",
"ic": "I see",
"idk": "I don't know",
"imao": "in my arrogant opinion",
"imnsho": "in my not so humble opinion",
"imo": "in my opinion",
"iow": "in other words",
"ipn": "I’m posting naked",
"irl": "in real life",
"jk": "just kidding",
"l8r": "later",
"ld": "later, dude",
"ldr": "long distance relationship",
"llta": "lots and lots of thunderous applause",
"lmao": "laugh my ass off",
"lmirl": "let's meet in real life",
"lol": "laugh out loud",
"ltr": "longterm relationship",
"lulab": "love you like a brother",
"lulas": "love you like a sister",
"luv": "love",
"m/f": "male or female",
"m8": "mate",
"milf": "mother I would like to fuck",
"oll": "online love",
"omg": "oh my god",
"otoh": "on the other hand",
"pir": "parent in room",
"ppl": "people",
"r": "are",
"rofl": "roll on the floor laughing",
"rpg": "role playing games",
"ru": "are you",
"shid": "slaps head in disgust",
"somy": "sick of me yet",
"sot": "short of time",
"thanx": "thanks",
"thx": "thanks",
"ttyl": "talk to you later",
"u": "you",
"ur": "you are",
"uw": "you’re welcome",
"wb": "welcome back",
"wfm": "works for me",
"wibni": "wouldn't it be nice if",
"wtf": "what the fuck",
"wtg": "way to go",
"wtgp": "want to go private",
"ym": "young man",
"gr8": "great"
}


emoticon_dict = {
":)": "happy",
":‑)": "happy",
":-]": "happy",
":-3": "happy",
":->": "happy",
"8-)": "happy",
":-}": "happy",
":o)": "happy",
":c)": "happy",
":^)": "happy",
"=]": "happy",
"=)": "happy",
"<3": "happy",
":-(": "sad",
":(": "sad",
":c": "sad",
":<": "sad",
":[": "sad",
">:[": "sad",
":{": "sad",
">:(": "sad",
":-c": "sad",
":-< ": "sad",
":-[": "sad",
":-||": "sad"
}